server:
  port: 8080
spring:
  cache:
    redis:
      time-to-live: 1800000
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  application:
    #?????
    name: reggie_takeout
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 1qaz2wsx
mybatis-plus:
  configuration:
    #????????????????????????????????????????????
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
reggie:
  path: /Users/roy/Documents/reggie-code/